name: Trigger Vercel Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy Hook
        if: ${{ secrets.VERCEL_DEPLOY_HOOK_URL != '' }}
        run: |
          echo "Calling Vercel deploy hook..."
          curl -sS -X POST "$VERCEL_DEPLOY_HOOK_URL"
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
